export const TASK_ACTION_TYPES = {
    SET_LOADING: "SET_LOADING",

    LOAD_TASKS_SUCCESS: "LOAD_TASKS_SUCCESS",
    LOAD_TASKS_FAILURE: "LOAD_TASKS_FAILURE",

    CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",

    UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",

    DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS"
};

export const VALIDATION = {
    TITLE_MAX_LENGTH: 100,
    DESCRIPTION_MAX_LENGTH: 1000
};